config/routes.rb
Rails.application.routes.draw do
  resources :questions
  devise_for :users

  root 'questions#index'

  put '/questions/:id/start_screenshare', to: 'questions#start_screenshare', as: 'start_screenshare'
  put '/questions/:id/finish_screenshare', to: 'questions#finish_screenshare', as: 'finish_screenshare'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  def type_options 
    [
      'SS',
      'Not Supported',
      'Unable to SS', 
      'Chat-Dispatch',
      'Chat-Sync',
      'No Answer', 
      'Duplicate'
    ]
  end

  def start_screenshare
    self.question_type = 'SS'
    self.start_share = Time.zone.now()
    self.save
  end

  def finish_screenshare 
    self.end_share = Time.zone.now()
    self.save
  end

  def new_start_share=(new_time)
    old_time = self.start_share
    hours = Integer(new_time.split(':')[0])
    minutes = Integer(new_time.split(':')[1])
    new_time = DateTime.new(old_time.year, old_time.month, old_time.day, hours, minutes, 0, Rational(-5,24))
    self.start_share = new_time 
    self.save
  end

  def new_end_share=(new_time)
    old_time = self.end_share
    hours = Integer(new_time.split(':')[0])
    minutes = Integer(new_time.split(':')[1])
    new_time = DateTime.new(old_time.year, old_time.month, old_time.day, hours, minutes, 0, Rational(-5,24))
    self.end_share = new_time 
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :start_screenshare, :finish_screenshare, :destroy]
  def index 
    @questions = Question.all
  end

  def update 
    @question.update(question_params)
    respond_to do |format|
      format.js { render json: @question }
    end
  end

  def start_screenshare 
    @question.start_screenshare
    respond_to do |format|
      format.js {}
      format.json { render json: @question }
    end
  end

  def finish_screenshare 
    @question.finish_screenshare
    respond_to do |format|
      format.js {}
      format.json { render json: @question }
    end
  end

  private 

  def set_question 
    @question = Question.find_by(id: params[:id])
  end

  def question_params
    params.require(:question).permit(:time_asked, :question_type, :asker_name, :github_username, :email, :question_link, :learn_expert, :new_start_share, :new_end_share, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnExpertHelper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_finish_screenshare_form.html.erb
<% if has_finished %>
  <%= form_tag question_path(question), method: 'put', remote: true, class: 'edit-finish-screenshare-form' do %>
    <%= time_field_tag 'question[new_end_share]', question.end_share.strftime('%H:%M'), class: 'h2 border-box' %>
    <%= submit_tag 'finish', class: 'dn' %>
  <% end %>
<% else %>
  <%= form_tag finish_screenshare_path(question), method: 'put', remote: true, class: 'finish-screenshare-form' do %>
    <%= time_field_tag :end_share, '', class: 'dn' %>
    <%= submit_tag 'finish', class: 'h2' %>
  <% end %>
<% end %>

app/views/questions/_start_screenshare_form.html.erb
<% if has_started %>
  <%= form_tag question_path(question), method: 'put', remote: true, class: 'edit-start-screenshare-form' do %>
    <%= time_field_tag 'question[new_start_share]', question.start_share.strftime('%H:%M'), class: 'h2 border-box' %>
    <%= submit_tag 'start', class: 'dn' %>
  <% end %>
<% else %>
  <%= form_tag start_screenshare_path(question), method: 'put', remote: true, class: 'start-screenshare-form' do %>
    <%= time_field_tag :start_share, '', class: 'dn' %>
    <%= submit_tag 'start', class: 'h2' %>
  <% end %>
<% end %>

app/views/questions/finish_screenshare.js.erb
$('.question-<%= @question.id %> .finish-screenshare-form')
  .hide()
  .after("<%= escape_javascript (render partial: 'questions/finish_screenshare_form', locals: { question: @question, has_finished: true } ) %>")

app/views/questions/index.html.erb
<div class="ph4">
  <h1>Questions</h1>
  <ul class="list pl0 cf">
    <li class="headers h2 b cf">
      <div class="fl w-10">Time Asked</div>
      <div class="fl w-10">Type</div>
      <div class="fl w-10">GH Username</div>
      <div class="fl w-10">Asker Name</div>
      <div class="fl w-20">Asker Email</div>
      <div class="fl w-10">Learn Expert</div>
      <div class="fl w-10">SS Start</div>
      <div class="fl-w-10">SS Finish</div>
    </li>
  <% @questions.each do |question| %>
    <li class="question-<%= question.id %> cf bb b--light-gray pt1">
      <div class="fl h2 pv1 w-10 time-asked">
        <%= link_to question.time_asked.strftime('%h %d, %H:%M'), question.question_link %>
      </div>
      <div class="fl h2 pv1 w-10 question-type f6">
        <%= form_tag question_path(question), method: 'put', remote: true, class: 'edit_question_type' do %>
          <% select("question", "question_type", question.type_options.collect {|o| [ o, o ] }, {selected: question.question_type, include_blank: true})%>
        <% end %>
      </div>
      <div class="fl h2 pv1 w-10 github-username">
        <%= question.github_username || '..' %>
      </div>
      <div class="fl h2 pv1 w-10 asker-name">
        <%= question.asker_name || '..' %>
      </div>
      <div class="fl h2 pv1 w-20 asker-email">
        <%= question.email || '..' %>
      </div>
      <div class="fl h2 w-10 learn-expert f6">
        <%= form_tag question_path(question), method: 'put', remote: true, class: 'edit-learn-expert-form pr2' do %>
          <%= text_field_tag 'question[learn_expert]', question.learn_expert, class: 'w-100 h2' %>
        <% end %>
        
      </div>
      <div class="fl h2 w-10 screen-share-start f6">
        <% if question.start_share %>
          <%= render partial: 'questions/start_screenshare_form', locals: { question: question, has_started: true } %>
        <% else %>
          <%= render partial: 'questions/start_screenshare_form', locals: { question: question, has_started: false } %>
        <% end %>
      </div>
      <div class="fl h2 w-10 screen-share-finish f6">
        <% if question.end_share %>
          <%= render partial: 'questions/finish_screenshare_form', locals: { question: question, has_finished: true } %>
        <% else %>
          <%= render partial: 'questions/finish_screenshare_form', locals: { question: question, has_finished: false } %>
        <% end %>
      </div>
      <div class="fl h2 w-10 actions">
        <%= link_to 'Edit', edit_question_path(question), remote: true %>
      </div>
    </li>
  <% end %>
  </ul>
</div>

app/views/questions/start_screenshare.js.erb
$('.question-<%= @question.id %> .start-screenshare-form')
  .hide()
  .after("<%= escape_javascript render partial: 'questions/start_screenshare_form', locals: { question: @question, has_started: true } %>")
$('.question-<%= @question.id %> select').val('<%= @question.question_type %>')